FROM python:3 as build
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/

RUN mkdir /code/static

RUN python manage.py collectstatic

# Serve using nginx
FROM nginx:latest
EXPOSE 82

COPY --from=build /code/static /usr/share/nginx/html/static

COPY nginx-static.conf /etc/nginx/conf.d/default.conf