# Generated by Django 2.2.5 on 2019-10-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTrack',
            fields=[
                ('videoId', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Youtube Video ID')),
                ('state', models.CharField(choices=[('DRAFT', 'DRAFT'), ('DONE', 'DONE')], max_length=10)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField(blank=True, null=True)),
                ('released', models.IntegerField(blank=True, null=True)),
                ('cover', models.BooleanField(blank=True, default=False)),
                ('is_finnish', models.BooleanField(blank=True, null=True)),
                ('rule10s', models.BooleanField(blank=True, default=False)),
                ('disliked', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=255)),
                ('feat', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
